#!/usr/bin/env php
<?php

var_dump(__DIR__);
die;

require __DIR__.'/vendor/autoload.php';

use Cyno\Console\Application;

if (\PHP_VERSION_ID < 80000) {
    fwrite(STDERR, 'CYNO required a PHP version of 8.0.0 or higher.');
    exit(1);
}

$application = new Application();
$application->run();