#!/usr/bin/env php
<?php

(function () {
    $possibleFiles = [
        __DIR__ . '/../../autoload.php',
        __DIR__ . '/../autoload.php',
        __DIR__ . '/vendor/autoload.php'
    ];

    $file = null;

    // Let composer figure out where the autoload is located.
    foreach ($possibleFiles as $possibleFile) {
        if (file_exists($possibleFile)) {
            $file = $possibleFile;

            break;
        }
    }

    if (null === $file) {
        throw new RuntimeException('Unable to locate autoload.php file.');
    }

    require_once $file;
})();

use Cyno\Console\Application;

if (\PHP_VERSION_ID < 80000) {
    fwrite(STDERR, 'CYNO required a PHP version of 8.0.0 or higher.');
    exit(1);
}

$application = new Application();
$application->run();